"""VectorMemory — ChromaDB-backed semantic memory per agent.

Each agent gets its own ChromaDB collection, enabling independent memory
namespaces with cosine similarity search and metadata filtering.

Usage::

    vm = VectorMemory(persist_dir="/tmp/hermes/chroma")
    vm.add(MemoryEntry(content="Claude is an AI assistant", agent_id="agent_1"))
    results = vm.query("AI assistant", agent_id="agent_1", n_results=5)
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import structlog

from hermes_memory.schemas import MemoryEntry, MemoryQueryResult

log = structlog.get_logger(__name__)

try:
    import chromadb
    from chromadb.config import Settings as ChromaSettings

    _CHROMA_AVAILABLE = True
except ImportError:
    _CHROMA_AVAILABLE = False
    log.warning("chromadb not installed — VectorMemory will raise on use")


_DEFAULT_COLLECTION_PREFIX = "hermes_agent_"
_DEFAULT_N_RESULTS = 10


class VectorMemory:
    """Persistent vector memory backed by ChromaDB.

    One ChromaDB collection is created per agent (named
    ``hermes_agent_<agent_id>``).  Embeddings are generated by ChromaDB's
    default embedding function (sentence-transformers/all-MiniLM-L6-v2) unless
    an external embedding function is provided.

    Parameters
    ----------
    persist_dir:
        Directory where ChromaDB stores its data on disk.
    embedding_function:
        Optional custom ChromaDB embedding function.  Defaults to the
        ``DefaultEmbeddingFunction`` built into ChromaDB.
    """

    def __init__(
        self,
        persist_dir: str | Path,
        embedding_function: Any = None,
    ) -> None:
        if not _CHROMA_AVAILABLE:
            raise ImportError(
                "chromadb is required for VectorMemory. Install it with: pip install chromadb"
            )
        self._persist_dir = Path(persist_dir)
        self._persist_dir.mkdir(parents=True, exist_ok=True)
        self._client = chromadb.PersistentClient(
            path=str(self._persist_dir),
            settings=ChromaSettings(anonymized_telemetry=False),
        )
        self._ef = embedding_function
        self._collections: dict[str, Any] = {}

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def add(self, entry: MemoryEntry) -> str:
        """Add a memory entry to the agent's collection.

        Parameters
        ----------
        entry:
            The :class:`MemoryEntry` to store.  ``entry.agent_id`` determines
            the collection.

        Returns
        -------
        str
            The stable ID of the stored entry.
        """
        col = self._get_or_create_collection(entry.agent_id)
        metadata = {**entry.metadata, "agent_id": entry.agent_id}

        col.upsert(
            ids=[entry.id],
            documents=[entry.content],
            metadatas=[metadata],
        )
        log.debug(
            "vector_memory.added",
            id=entry.id,
            agent_id=entry.agent_id,
            content_len=len(entry.content),
        )
        return entry.id

    def query(
        self,
        text: str,
        agent_id: str,
        n_results: int = _DEFAULT_N_RESULTS,
        where: dict[str, Any] | None = None,
    ) -> list[MemoryQueryResult]:
        """Semantic search for memories similar to *text*.

        Parameters
        ----------
        text:
            Query text to embed and search against.
        agent_id:
            Restricts search to this agent's collection.
        n_results:
            Maximum number of results to return.
        where:
            Optional ChromaDB ``where`` filter dict for metadata filtering.

        Returns
        -------
        list[MemoryQueryResult]
            Results sorted by relevance (highest first).
        """
        col = self._get_or_create_collection(agent_id)
        count = col.count()
        if count == 0:
            return []

        actual_n = min(n_results, count)
        kwargs: dict[str, Any] = {
            "query_texts": [text],
            "n_results": actual_n,
            "include": ["documents", "metadatas", "distances"],
        }
        if where:
            kwargs["where"] = where

        result = col.query(**kwargs)

        docs = result["documents"][0]
        metas = result["metadatas"][0]
        dists = result["distances"][0]
        ids = result["ids"][0]

        out: list[MemoryQueryResult] = []
        for doc_id, doc, meta, dist in zip(ids, docs, metas, dists, strict=True):
            entry_meta = {k: v for k, v in meta.items() if k != "agent_id"}
            entry = MemoryEntry(
                id=doc_id,
                content=doc,
                metadata=entry_meta,
                agent_id=str(meta.get("agent_id", agent_id)),
            )
            out.append(
                MemoryQueryResult(
                    entry=entry,
                    distance=float(dist),
                    relevance_score=max(0.0, 1.0 - float(dist)),
                )
            )
        return out

    def delete(self, entry_id: str, agent_id: str) -> bool:
        """Remove an entry by ID from the agent's collection.

        Returns
        -------
        bool
            ``True`` if the entry existed and was deleted.
        """
        col = self._get_or_create_collection(agent_id)
        try:
            col.delete(ids=[entry_id])
            log.debug("vector_memory.deleted", id=entry_id, agent_id=agent_id)
            return True
        except Exception:
            log.debug("vector_memory.delete_miss", id=entry_id, agent_id=agent_id)
            return False

    def count(self, agent_id: str) -> int:
        """Return the number of entries in the agent's collection."""
        col = self._get_or_create_collection(agent_id)
        return int(col.count())

    def clear_agent(self, agent_id: str) -> None:
        """Delete the entire collection for *agent_id*."""
        col_name = self._collection_name(agent_id)
        try:
            self._client.delete_collection(col_name)
            self._collections.pop(agent_id, None)
            log.info("vector_memory.cleared", agent_id=agent_id)
        except Exception:
            log.debug("vector_memory.clear_miss", agent_id=agent_id)

    # ------------------------------------------------------------------ #
    # Internal helpers                                                     #
    # ------------------------------------------------------------------ #

    def _collection_name(self, agent_id: str) -> str:
        # ChromaDB collection names must be 3-63 chars, alphanumeric + hyphens.
        safe = hashlib.sha256(agent_id.encode()).hexdigest()[:16]
        return f"{_DEFAULT_COLLECTION_PREFIX}{safe}"

    def _get_or_create_collection(self, agent_id: str) -> Any:
        if agent_id not in self._collections:
            name = self._collection_name(agent_id)
            kwargs: dict[str, Any] = {
                "name": name,
                "metadata": {"hnsw:space": "cosine"},
            }
            if self._ef is not None:
                kwargs["embedding_function"] = self._ef
            self._collections[agent_id] = self._client.get_or_create_collection(**kwargs)
        return self._collections[agent_id]
